# Generated by Django 5.1.3 on 2024-11-13 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0004_remove_playlist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='playlist_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_song_deezer', models.BigIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musify.users', verbose_name='musify_users')),
            ],
        ),
    ]
