# Generated by Django 5.1.3 on 2024-11-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0006_playlist_user_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist_user',
            name='playlist',
        ),
    ]
