# Generated by Django 5.1.3 on 2024-11-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0008_playlist_users_delete_playlist_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='playlist_users',
            new_name='playlist_user',
        ),
    ]
