# Generated by Django 5.1.3 on 2024-12-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0018_playlistuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistuser',
            name='user',
        ),
    ]
