# Generated by Django 5.1.3 on 2024-12-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0016_remove_playlistuser_date_playlistuser_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistuser',
            name='user',
        ),
    ]
