# Generated by Django 5.1.3 on 2025-02-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0019_remove_playlistuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='type',
            field=models.CharField(choices=[('artist', 'Artist'), ('track', 'Track')], max_length=10),
        ),
    ]
